#!/bin/bash
source $(dirname "$0")/config.sh $1
echo "container_name: $CONTAINER_NAME"
echo "port: $PORT"

ROOT="$(pwd)/$(dirname "$0")"

mkdir -p "${ROOT}/log"

docker run -d --name $CONTAINER_NAME -it -p $PORT:50051 \
  --volumes-from aws-config \
  daangn/starspace-server server.py \
    --header-lines-count 4 \
    --debug embed_doc_extend s3://daangn/ml/similar-feedbacks/models/starspace-production
